### ISSUE TITLE
The testing framework reported an exit code of 143

### ISSUE THREAD

**Issue by limetec** [padraic/humbug#158]
I installed PHPUnit 4.8.10 and Humbug 1.0-dev with Composer.
My phpunit.xml looks the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>
    <testsuites>
        <testsuite name="All Unit tests">
            <directory suffix="Test.php">./test/lib</directory>
            <exclude>./test/lib/processes/actions/EditLaboratories/groups/EditGroupsTreeControllerTest.php</exclude>
        </testsuite>
    </testsuites>
</phpunit>
```

When I run "vendor/bin/phpunit" all tests run fine:
```
.......................................

Time: 249 ms, Memory: 6.75Mb

OK (39 tests, 163 assertions)
```

But when I start Humbug with "vendor/bin/humbug" I get:
```

 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/ 
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------]  1 sec

Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 143.
The testing framework ran into a failure or error. Refer to output below.
Stdout:
   > TAP version 13
   > 
Stderr:
   > PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Trying to get property of non-object' in /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/Util/XML.php:224
   > Stack trace:
   > #0 /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/Util/XML.php(224): lib\common\classes\Logger->phpErrorHandler(8, 'Trying to get p...', '/home/jan/Phpst...', 224, Array)
   > #1 /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/Util/Configuration.php(336): PHPUnit_Util_XML::xmlToVariable(Object(DOMElement))
   > #2 /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(761): PHPUnit_Util_Configuration->getListenerConfiguration()
   > #3 /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(145): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
   > #4 /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
   > #5 /home/jan/PhpstormProjects/labac in /home/jan/PhpstormProjects/labaccess/vendor/phpunit/phpunit/src/Util/XML.php on line 224
   > 
```

My humbug.json.dist looks like this:
```
{
    "source": {
        "directories": [
            "lib"
        ]
    },
    "timeout": 10,
    "logs": {
        "text": "humbuglog.txt"
    }
}
```

Have I configured something wrong or is there an error in Humbug / PHPUnit?

**Comment by MarkRedeman** [comment]
I am not sure why but for me this only happens when humbug is not using my global `phpunit` executable even though both the phpunit required in my global `composer.json` and the local one has the `~4.8` version requirement.

In most cases you can still run humbug if you change your `composer.json` if you remove the `phpunit` executable from your vendor dir.

**Comment by nickel715** [comment]
I've the same issue, if I downgrade phpunit to 4.7.* everthing works fine

**Comment by samsonasik** [comment]
ping @padraic  ;)

**Comment by sandrokeil** [comment]
@padraic I've have the same issue with PHPUnit 4.8 and PHP 5.6. The class is `\Humbug\Phpunit\Logger\JsonLogger`. Any ideas?

```bash
Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 255.
Stdout:
   > TAP version 13
   > 
   > Notice: Trying to get property of non-object in /app/vendor/phpunit/phpunit/src/Util/XML.php on line 235
   > 
   > Call Stack:
   >     0.0005     221432   1. {main}() /app/vendor/phpunit/phpunit/phpunit:0
   >     0.0125     668640   2. PHPUnit_TextUI_Command::main() /app/vendor/phpunit/phpunit/phpunit:47
   >     0.0125     669072   3. PHPUnit_TextUI_Command->run() /app/vendor/phpunit/phpunit/src/TextUI/Command.php:100
   >     0.0987    1929288   4. PHPUnit_TextUI_TestRunner->doRun() /app/vendor/phpunit/phpunit/src/TextUI/Command.php:149
   >     0.0987    1930584   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:153
   >     0.0989    1934752   6. PHPUnit_Util_Configuration->getListenerConfiguration() /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:772
   >     0.0990    1938720   7. PHPUnit_Util_XML::xmlToVariable() /app/vendor/phpunit/phpunit/src/Util/Configuration.php:342
   > 
   > 
   > Warning: Invalid argument supplied for foreach() in /app/vendor/phpunit/phpunit/src/Util/XML.php on line 238
   > 
   > Call Stack:
   >     0.0005     221432   1. {main}() /app/vendor/phpunit/phpunit/phpunit:0
   >     0.0125     668640   2. PHPUnit_TextUI_Command::main() /app/vendor/phpunit/phpunit/phpunit:47
   >     0.0125     669072   3. PHPUnit_TextUI_Command->run() /app/vendor/phpunit/phpunit/src/TextUI/Command.php:100
   > [...Middle of output removed by Humbug...]
   >     0.0996    1960216   9. Humbug\Phpunit\Logger\JsonLogger->write() /app/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Logger/JsonLogger.php:31
   >     0.0996    1960368  10. file_put_contents() /app/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Logger/JsonLogger.php:61
   > 
   > 
   > Fatal error: Uncaught exception 'LogicException' with message 'JsonLogger requires logs target path' in /app/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Logger/JsonLogger.php on line 24
   > 
   > LogicException: JsonLogger requires logs target path in /app/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Logger/JsonLogger.php on line 24
   > 
   > Call Stack:
   >     0.0005     221432   1. {main}() /app/vendor/phpunit/phpunit/phpunit:0
   >     0.0125     668640   2. PHPUnit_TextUI_Command::main() /app/vendor/phpunit/phpunit/phpunit:47
   >     0.0125     669072   3. PHPUnit_TextUI_Command->run() /app/vendor/phpunit/phpunit/src/TextUI/Command.php:100
   >     0.0987    1929288   4. PHPUnit_TextUI_TestRunner->doRun() /app/vendor/phpunit/phpunit/src/TextUI/Command.php:149
   >     0.0987    1930584   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:153
   >     0.0989    1934752   6. PHPUnit_Util_Configuration->getListenerConfiguration() /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:772
   >     0.0990    1938720   7. PHPUnit_Util_XML::xmlToVariable() /app/vendor/phpunit/phpunit/src/Util/Configuration.php:342
   >     0.0994    1943248   8. ReflectionClass->newInstanceArgs() /app/vendor/phpunit/phpunit/src/Util/XML.php:245
   >     0.0994    1943376   9. Humbug\Phpunit\Logger\JsonLogger->__construct() /app/vendor/phpunit/phpunit/src/Util/XML.php:245
```

**Comment by MarkRedeman** [comment]
After doing some more research it seems that the bug was introduced in PHPUnit version 4.8.9, more specifically by [not preserving whitespace](https://github.com/sebastianbergmann/phpunit/commit/73fad41#diff-465c56d147574c37dbb58c3b97812a09R104).

If preserving whitespace is enabled everything works correctly, though I do not yet understand why. The configuration loader test (`Humbug\Test\Adapter\Phpunit\ConfigurationLoaderTest::testShouldLoadDomDocument`) is expecting that whitespace should not be preserved (Though I'm not 100% sure that this configuration should have any influence on phpunit).

I've currently tracked it down to a potential bug in the generated `phpunit.xml` file that is stored in the tmp folder.
This is what the file looks like,
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false" backupStaticAttributes="false" colors="true" convertErrorsToExceptions="true" convertNoticesToExceptions="true" convertWarningsToExceptions="true" processIsolation="false" stopOnFailure="false" syntaxCheck="false" bootstrap="/tmp/humbug.phpunit.bootstrap.php" cacheTokens="false">
  <testsuites>
    <testsuite name="php-tmdb-api Test Suite">
      <directory>/home/mark/Projects/webdev/contributions/api/test/Tmdb</directory>
    </testsuite>
  </testsuites>
  <groups>
    <exclude>
      <group>functional</group>
    </exclude>
  </groups>
  <logging>
    <log type="coverage-php" target="/tmp/humbug/coverage.humbug.php"/>
    <log type="coverage-text" target="/tmp/humbug/coverage.humbug.txt"/>
    <log type="junit" target="/tmp/humbug/junit.humbug.xml"/>
  </logging>
  <filter>
    <whitelist>
      <directory suffix=".php">/home/mark/Projects/webdev/contributions/api/lib</directory>
    </whitelist>
  </filter>
  <listeners>
    <listener class="\MyBuilder\PhpunitAccelerator\TestListener">
      <arguments>
        <boolean>true</boolean>
      </arguments>
    </listener>
    <listener class="\Humbug\Phpunit\Listener\TimeCollectorListener">
      <arguments>
        <object class="\Humbug\Phpunit\Logger\JsonLogger">
          <arguments>
            <string>/tmp/humbug/phpunit.times.humbug.json</string>
          </arguments>
        </object>
        <integer>0</integer>
      </arguments>
    </listener>
  </listeners>
</phpunit>
```
If I run phpunit with `$document->preserveWhiteSpace = true;` (that is not using humbug but just using `vendor/bin/phpunit`) then it won't throw an error, but when whitespace is not preserved we get the same error as has been shown at the start of this issue.

After some additional trial and error I've found that the bug is introduced when the whitespace around the arguments of the `JsonLogger` have been removed, that is if it looks like this:
```
<object class="\Humbug\Phpunit\Logger\JsonLogger"><arguments><string>/tmp/humbug/phpunit.times.humbug.json</string></arguments></object>
```
It starts to throw errors as soon as there is no whitespace between the `<object ><arguments>` tags.


After doing some additional debugging on in PHPUnit I've found that [this line](https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/XML.php#L213) is asking for the the child with index 1, which works if there is whitespace between `<object>` and `<arguments>` (in this case the length of `childnodes` is 3), but when we omit the whitespace the length of the `childnodes` is 1 and so the 0th index should be used.

I still don't fully understand why this is happening and whether this is a bug with Humbug's configuration or with PHPUnit's parsing of the xml files.
Hopefully someone else can give some input so we can get this issue solved. :)

**Comment by MarkRedeman** [comment]
This issue is related to a [bug in PHPUnit](https://github.com/sebastianbergmann/phpunit/issues/1873).

**Comment by fezfez** [comment]
Same issue here :cry:

**Comment by MarkRedeman** [comment]
While waiting for a fix, you should be able to use [my branch](https://github.com/MarkRedeman/humbug/tree/fix-phpunit-listener). It works for any PHPUnit version >= 4.5.

**Comment by padraic** [comment]
@MarkRedeman I assume this one can be closed?

**Comment by MarkRedeman** [comment]
Yep this can be closed.
