### ISSUE TITLE
Running Humbug on Humbug

### ISSUE THREAD

**Issue by rollenes** [padraic/humbug#98]
I get lots of errors running Humbug on Humbug. Errors are connected with phpunit-extensions installed some time ago.

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'FastestFirstFilter has encountered an unlogged test suite which cannot be sorted' in /home/rolen/php/humbug/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Filter/TestSuite/FastestFirstFilter.php:30
Stack trace:
#0 [internal function]: Humbug\Phpunit\Filter\TestSuite\FastestFirstFilter->Humbug\Phpunit\Filter\TestSuite\{closure}(Object(PHPUnit_Framework_TestSuite), Object(PHPUnit_Framework_TestSuite))
#1 /home/rolen/php/humbug/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Filter/TestSuite/FastestFirstFilter.php(41): usort(Array, Object(Closure))
#2 /home/rolen/php/humbug/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Listener/FilterListener.php(61): Humbug\Phpunit\Filter\TestSuite\FastestFirstFilter->filter(Array)
#3 /home/rolen/php/humbug/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Listener/FilterListener.php(47): Humbug\Phpunit\Listener\FilterListener->filterSuites(Array)
#4 /home/rolen/php/humbug/vendor/phpunit/phpunit/src/Framew in /home/rolen/php/humbug/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Filter/TestSuite/FastestFirstFilter.php on line 30
```

This error occurs 214 times. See https://gist.github.com/rollenes/fd4930184ad7e2375de5#file-humbug-issue-txt

FastestFirstFilter is not able to find time logs for specific tests in phpunit.times.humbug.json.

After some analysis I found that this file(phpunit.times.humbug.json) is changing while running humbug.

I run tail on phpunit.times.humbug.json. See https://gist.github.com/rollenes/fd4930184ad7e2375de5#file-humbug-times-tail-log

It appears to truncate file many times while running.

So I simply run phpunit on humbug test harness and effect was the same. It overrides phpunit.times.humbug.json several times.
See tail below:

```
rolen@rollen:/tmp $ tail -f phpunit.times.humbug.json 
{
    "suites": [],
    "tests": {
        "MM1_MathTest": [
            {
                "title": "testAdds",
                "time": 0.010890007019043
            }
        ]
    }
}.0039820671081543
            }
        ]
    }
}tail: phpunit.times.humbug.json: file truncated
tail: phpunit.times.humbug.json: file truncated
{
    "suites": [],
    "tests": {
        "ExceptionTest": [
            {
                "title": "testSomeException",
                "time": 0.0022640228271484
            }
        ]
    }
}tail: phpunit.times.humbug.json: file truncated
```

So each time tests are run in humbug as a background phpunit process it truncates file and pushes new content to phpunit.times.humbug.json.

I tracked those tests under `Humbug\Test\Adapter\PhpunitTest`. Skipping this tests made possible to run phpunit without affecting phpunit.times.humbug.json.
Running humbug then also did not affected this file. And all errors disappeared. 
But I didn`t want to skip them...

After some another analysis of `Humbug\Test\Adapter\PhpunitTest` I found that those test writes all of its contents to cacheDirectory. 
So I changed it, and unskipped those tests. 
Phpunit run didnt affects phpunit.times.humbug.json .So problem should disappear...

But I still get the same errors running Humbug on Humbug:
```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'FastestFirstFilter has encountered an unlogged test suite which cannot be sorted' in /home/rolen/php/humbug/vendor/padraic/phpunit-extensions/src/Humbug/Phpunit/Filter/TestSuite/FastestFirstFilter.php:30
```
Also tail of phpunit.times.humbug.json behaved in the same way(truncated and replaced content). 

Digging dipper...

First some cleanups - I left those new cache folders in test suites so I thought it would be nice to remove it in tearDown.

PhpUnit failed:
```
rmdir(/tmp/8583355): Directory not empty

rolen@rollen:~/php/humbug (master) $ ls /tmp/5117136
coverage.humbug.php  coverage.humbug.txt  phpunit.humbug.xml
```
So there are some files in this place after running phpunit. This is some kind of side effect, so I remove this files.
PhpUnit run: passes 
Humbug on humbug: no changes... 
Still lots of errors with FastestFirstFilter and tail of phpunit.times.humbug.json reports to be truncated many times.

Lets debug then, and trace changes in files with side effects mentioned before:
- phpunit.humbug.xml 
- phpunit.times.humbug.json

with debugging points after initial check is done and after each mutant process is executed. No results as those processes are run in background and from debugging tools its hard to jump into new paraller process.

I put some logs here and there...

It turns out that one of mutant was creating phpunit.humbug.xml with content bellow:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.4/phpunit.xsd" backupGlobals="false" backupStaticAttributes="false" colors="true" convertErrorsToExceptions="true" convertNoticesToExceptions="true" convertWarningsToExceptions="true" processIsolation="false" stopOnFailure="false" syntaxCheck="false" bootstrap="/tmp/humbug.phpunit.bootstrap.php" cacheTokens="false">

    <testsuites>
        <testsuite name="Test Suite">
            
        <directory>/home/rolen/php/humbug/tests/Adapter/_files/phpunit</directory></testsuite>
    </testsuites>

    
    
<listeners><listener class="\MyBuilder\PhpunitAccelerator\TestListener"><arguments><boolean>true</boolean></arguments></listener><listener class="\Humbug\Phpunit\Listener\TimeCollectorListener"><arguments><object class="\Humbug\Phpunit\Logger\JsonLogger"><arguments><string>/tmp/1514814/phpunit.times.humbug.json</string></arguments></object></arguments></listener></listeners><logging><log type="coverage-php" target="/tmp/1514814/coverage.humbug.php"/><log type="coverage-text" target="/tmp/1514814/coverage.humbug.txt"/></logging><filter><whitelist/></filter></phpunit>
```

This mutant was *not* written in humbuglog.txt:

```
XmlConfiguration:
-        self::$dom->preserveWhiteSpace = false;
+        self::$dom->preserveWhiteSpace = true;
```

Running phpunit against phpunit.humbug.xml produced:
```
rolen@rollen:~/php/humbug (master) $ vendor/bin/phpunit -c phpunit.humbug.xml 
PHP Notice:  Trying to get property of non-object in /home/rolen/php/humbug/vendor/phpunit/phpunit/src/Util/XML.php on line 231
PHP Stack trace:
PHP   1. {main}() /home/rolen/php/humbug/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main($exit = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run($argv = *uninitialized*, $exit = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/Command.php:103
PHP   4. PHPUnit_TextUI_TestRunner->doRun($suite = *uninitialized*, $arguments = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/Command.php:151
PHP   5. PHPUnit_TextUI_TestRunner->handleConfiguration($arguments = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:153
PHP   6. PHPUnit_Util_Configuration->getListenerConfiguration() /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:687
PHP   7. PHPUnit_Util_XML::xmlToVariable($element = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/Util/Configuration.php:339
PHP Warning:  Invalid argument supplied for foreach() in /home/rolen/php/humbug/vendor/phpunit/phpunit/src/Util/XML.php on line 234
PHP Stack trace:
PHP   1. {main}() /home/rolen/php/humbug/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main($exit = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run($argv = *uninitialized*, $exit = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/Command.php:103
PHP   4. PHPUnit_TextUI_TestRunner->doRun($suite = *uninitialized*, $arguments = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/Command.php:151
PHP   5. PHPUnit_TextUI_TestRunner->handleConfiguration($arguments = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:153
PHP   6. PHPUnit_Util_Configuration->getListenerConfiguration() /home/rolen/php/humbug/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:687
PHP   7. PHPUnit_Util_XML::xmlToVariable($element = *uninitialized*) /home/rolen/php/humbug/vendor/phpunit/phpunit/src/Util/Configuration.php:339
PHPUnit 4.4.5 by Sebastian Bergmann.

Configuration read from /home/rolen/php/humbug/phpunit.humbug.xml

.

Time: 10.25 seconds, Memory: 6.50Mb

OK (1 test, 1 assertion)

Generating code coverage report in PHP format ... done
```

and /tmp/phpunit.times.humbug.json was affected with content:
```
{
    "suites": {
        "MM1_MathTest": 0.012728929519653
    },
    "tests": {
        "MM1_MathTest": [
            {
                "title": "testAdds",
                "time": 0.012728929519653
            }
        ]
    }
}
```
Eureka!
All because of JsonLogger::__construct(), If there is no $target given it will write into /tmp/phpunit.times.humbug.json.
 
I changed logic in JsonLogger::__construct() and revert this mutant in codebase. 
Phpunit: failed with fatal error.
Humbug on humbug: no errors :) And phpunit.times.humbug.json was not changed since first run.

**Comment by rollenes** [comment]
To resolove it merge #99 is required.
And update of *phpunit-extensions* by https://github.com/padraic/phpunit-extensions/pull/2 is required.

**Comment by padraic** [comment]
Merged! Appreciate the debugging patience :). If this resolves the problem, I'll let you close the issue.

**Comment by rollenes** [comment]
After merge and update of phpunit-extensions via composer update I didn`t noticed this problem again.
